#+TITLE:Cognitive Systems Excercise 3 
#+AUTHOR: Maik Schünemann
#+email: maikschuenemann@gmail.com
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  de
#+OPTIONS:   H:3 num:t toc:t :nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME:
#+TAGS:  BlowerDoor(b) Suub(s) Uni(u) Home(h) Task(t) Note(n) Info(i)
#+TAGS: Changed(c) Project(p) Reading(r) Hobby(f) OpenSource(o) Meta(m)
#+SEQ_TODO: TODO(t) STARTED(s) WAITING(w) APPT(a) | DONE(d) CANCELLED(c) DEFERRED(f) NEXT(n)
#+STARTUP:showall
#+LaTeX_CLASS: uni
-----
* Excercise 1

** Concept of the extension
*** Additional Components
    We added group recognizer components to our cognitive
    architecture, one for each group of proximity.
    They extend the counting/recognizing visual routines - 
    functionality of excercise 2. 
*** Interplay between the components
    To model human behaviour, we only concentrate on the filled
    regions of the visual stimulus. We extended the peripheral view
    component to quickly scan the picture to find the regions of 
    the stimuli that are filled. 
    On this regions we invoke the actual algorithm to count the 
    groups (implemented in the components above).
    If we have found a non-empty cell our system looks at all adjacent
    cells if they also belong to the group. It does this until it has
    found the whole group the cell belongs to.
    It then continues looking for other groups but knows what cells it
    has looked at before and doesn't revisit them.
    The components for recognizing groups of proximity, color, shape 
    only behave differently when they decide whether the adjacent cell
    belongs to the same group or not

*** Examples: See the attached Screenshots

